apiVersion: v1
kind: Secret
metadata:
  name: api-managementz-secrets
  namespace: api-managementz
type: Opaque
stringData:
  AUTH_SECRET: change_me
  DB_USER: api_managementz
  DB_PASSWORD: api_managementz
  DB_NAME: api_managementz
  DB_SSLMODE: disable
